language: node_js
cache: npm
dist: bionic

branches:
  only:
  - master
  - /^release\/.*$/

stages:
  - check
  - test
  - cov

node_js:
  - 'lts/*'
  - 'node'

os:
  - linux
  - osx
  - windows

script: npm run test:node -- --cov
after_success: npx nyc report --reporter=text-lcov > coverage.lcov && npx codecov

jobs:
  include:
    - os: windows
      cache: false

    - stage: check
      script:
        - npx aegir dep-check
        - npm run lint

    - stage: test
      name: chrome
      addons:
        chrome: stable
      script: npx aegir test -t browser -t webworker

    - stage: test
      name: firefox
      addons:
        firefox: latest
      script: npx aegir test -t browser -t webworker -- --browser firefox

notifications:
  email: false